### ISSUE TITLE
window can no longer be moved

### ISSUE THREAD

**Issue by Nightwalker559** [Jods-GH/GroupFinderRIO#1]
### Description

hi, with the addon the windows can no longer be moved. i have elvui and windtools on it so i can move my windows. when i move it, it happens. there is no error message
![Screenshot 2024-07-21 193206](https://github.com/user-attachments/assets/30332754-941d-4492-8175-87dd007872b2)
![Screenshot 2024-07-21 193213](https://github.com/user-attachments/assets/f7c98241-2c49-4bc7-9822-73b4e0557ae2)

### World of Warcraft Flavor

Retail (Default)

### Reproduction Steps

use elvui and windtools, see if you can move the window

### Last Good Version

GroupFinderRio v1.0.1

**Comment by Jodsderechte** [comment]
since windtools seems to be entirely unusable i can't rly test this. But i've rewrote the spec window so i hope this is no longer the case if yes pleas reopen
