### ISSUE TITLE
Toggle for 'Enable Spec Priority' window

### ISSUE THREAD

**Issue by gregostrowski** [Jods-GH/GroupFinderRIO#10]
### Is your feature request related to a problem? Please describe.

Would like a way to hide the 'Enable Spec Priority' window when listing a group.

### Describe the solution you'd like

A toggle button in the options to show/hide this window.

### Additional context

I feel like the options added to the window, such as all the different sorting options, already provide enough to help me find the right candidates, i don't need this other option and it just adds clutter to my ui.

Thanks!

**Comment by Jodsderechte** [comment]
That is already an option
