### ISSUE TITLE
GroupFinderRio.lua:548: invalid order function for sorting

### ISSUE THREAD

**Issue by RavenDT** [Jods-GH/GroupFinderRIO#11]
### Description

N/A

### World of Warcraft Flavor

Retail (Default)

### Lua Error

4x GroupFinderRio/GroupFinderRio.lua:548: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@GroupFinderRio/GroupFinderRio.lua"]:548: in function <GroupFinderRio/GroupFinderRio.lua:542>
[string "=[C]"]: in function `LFGListUtil_SortSearchResults'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2569: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2566>
[string "=[C]"]: in function `LFGListSearchPanel_UpdateResultList'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2223: in function `onEvent'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:262: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:171>

Locals:
(*temporary) = <table> {
 1 = 6804
 2 = 6799
 3 = 6369
 4 = 6777
 5 = 6816
 6 = 6755
 7 = 6758
 8 = 6841
 9 = 6839
 10 = 6762
 11 = 6832
 12 = 6766
 13 = 6768
 14 = 6771
 15 = 6774
 16 = 6775
 17 = 6830
 18 = 6752
 19 = 6823
 20 = 6783
 21 = 6784
 22 = 6786
 23 = 6787
 24 = 6788
 25 = 6789
 26 = 6790
 27 = 6820
 28 = 6795
 29 = 6797
 30 = 6751
 31 = 6769
 32 = 6810
 33 = 6805
 34 = 6803
 35 = 6846
 36 = 6806
 37 = 6807
 38 = 6798
 39 = 6811
 40 = 6812
 41 = 6813
 42 = 6817
 43 = 6819
 44 = 6793
 45 = 6791
 46 = 6828
 47 = 6781
 48 = 6834
 49 = 6778
 50 = 6836
 51 = 6773
 52 = 6772
 53 = 6770
 54 = 6843
 55 = 6767
 56 = 6764
 57 = 6847
 58 = 6848
 59 = 6760
 60 = 6753
 61 = 6815
 62 = 6818
 63 = 6801
 64 = 6809
 65 = 6782
 66 = 6765
 67 = 6826
 68 = 6840
 69 = 6763
 70 = 6750
 71 = 6785
 72 = 6827
 73 = 6849
 74 = 6761
 75 = 6800
 76 = 6821
 77 = 6757
 78 = 6796
 79 = 6792
 80 = 6844
 81 = 6794
 82 = 6824
 83 = 6822
 84 = 6842
 85 = 6835
 86 = 6829
 87 = 6779
 88 = 6808
 89 = 6825
 90 = 6754
 91 = 6838
 92 = 6814
 93 = 6833
 94 = 6837
 95 = 6780
 96 = 6756
 97 = 6776
 98 = 6759
 99 = 6845
 100 = 6831
 101 = 6802
}
(*temporary) = 6369
(*temporary) = 6799
(*temporary) = nil

### Reproduction Steps

Happens when applying to groups while in a party with another member.

### Last Good Version

Unknown

**Comment by Jodsderechte** [comment]
thanks i'll look into it

**Comment by Jodsderechte** [comment]
Bonus question what were you applying for keys? raids? legacy raids? what was your group composition etc. the more info you have for me the better

**Comment by eicherj** [comment]
Hi, 
I have the same issue. I (mage) was with a friend (resto shaman), we were applying for m+ dungeons.

Greetings,
Johanna

**Comment by Jodsderechte** [comment]
I think it should be fixed in the next release but i have to tackle another todo first before i'm able to release it

**Comment by RavenDT** [comment]
> Bonus question what were you applying for keys? raids? legacy raids? what was your group composition etc. the more info you have for me the better

I was applying to Dungeon groups (Mythic+ specifically).

**Comment by Jodsderechte** [comment]
This should (hopefully) be fixed with newest release please reopen when it keeps happening on v1.1.8
