### ISSUE TITLE
Make a party fit filter option

### ISSUE THREAD

**Issue by mLgz0rn** [Jods-GH/GroupFinderRIO#14]
### Is your feature request related to a problem? Please describe.

Right now, it does not seem like there is an option to make your party fit when signing up for m+

### Describe the solution you'd like

Add an option to enable a party fit filter.
This removes listed groups which does not have space for your party roles.

### Additional context

Thank you! :D

**Comment by Jodsderechte** [comment]
The addon is primarily focused on adding score information (and sorting) Premade Group filter has the feature you want. I'll think about if it's worth adding this anyway but i do see an issue of feature creep where i'm reimplementing all the features PGF has which i don't rly want

**Comment by mLgz0rn** [comment]
> The addon is primarily focused on adding score information (and sorting) Premade Group filter has the feature you want. I'll think about if it's worth adding this anyway but i do see an issue of feature creep where i'm reimplementing all the features PGF has which i don't rly want

Yeah but it was more since you already got all the other filters, it kinda makes premade group filters not needed.
