### ISSUE TITLE
bug 11.0.7

### ISSUE THREAD

**Issue by Yotiki** [Jods-GH/GroupFinderRIO#16]
### Description

an error in Bugsack since 11.0.7

### World of Warcraft Flavor

Retail (Default)

### Lua Error

23x bad argument #1 to '?' (Usage: local activityInfo = C_LFGList.GetActivityInfoTable(activityID [, questID, showWarmode]))
[string "=[C]"]: in function `GetActivityInfoTable'
[string "@GroupFinderRio/GroupFinderRio.lua"]:370: in function <GroupFinderRio/GroupFinderRio.lua:365>
[string "=[C]"]: in function `LFGListSearchEntry_Update'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2619: in function `initializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:374: in function `InvokeInitializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:392: in function <...izzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua:391>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:395: in function `InvokeInitializers'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:718: in function `Update'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:234: in function `SetScrollPercentageInternal'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:160: in function `FullUpdateInternal'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:688: in function `FullUpdateInternal'
...
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:319: in function `SignalDataChangeEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:299: in function `SetDataProvider'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:639: in function `SetDataProvider'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2663: in function `LFGListSearchPanel_UpdateResults'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2593: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2589>
[string "=[C]"]: in function `LFGListSearchPanel_UpdateResultList'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2211: in function `onEvent'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:262: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:171>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local activityInfo = C_LFGList.GetActivityInfoTable(activityID [, questID, showWarmode]))"

### Reproduction Steps

Opened group finder - Dungeons

### Last Good Version

yes before was working fine

**Comment by Jodsderechte** [comment]
fixed in newest version thanks for reporting
