### ISSUE TITLE
Add Timed X Keys to track

### ISSUE THREAD

**Issue by oesi94** [Jods-GH/GroupFinderRIO#2]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add an option to track how many keys the applicant/group has timed a specific keyrange.

For example i timed 5x8 key,  20x11 keys and 1 16 key. i can choose between 5+ 10+ 15+ or select all.

It can show then somthing like 5x5+ 20x10+ 1x15+, used that from the weakaura https://wago.io/6-GG3RMcC

**Comment by Jodsderechte** [comment]
Space is kind of an issue. The WeakAuras has overlapping stuff everywhere which i'm not very keen on adding. Where exactly would you suggest this information to be displayed

![GroupFInderRioDungeonApplication](https://github.com/user-attachments/assets/ef25987b-f1ba-4323-b6bd-d5b7a7a53fd0)

**Comment by Jodsderechte** [comment]
added in [bae8807](https://github.com/Jods-GH/GroupFinderRIO/commit/bae8807fb6731d11473ed698a888fb39748cc27d) however you can't show all at the same time as there would be no space otherwise. Even like this it can be short and i might remove/change it again if it get's to anoying

**Comment by oesi94** [comment]
Oh i remember i had it simpler shown, for example blue was +5 and purple was +10, so i it would be then just 0 2 = 0x+5 and 2x+10

https://i.imgur.com/EqZT9aW.png here a screenshot. And would be cool if we could use it for the group category aswell, when im looking for a key. 

Ty for adding it :)

**Comment by Jodsderechte** [comment]
Ah hm that could be an idea to use colorcoding i'll think about it
