### ISSUE TITLE
Groups move when you click on them

### ISSUE THREAD

**Issue by Milky063** [Jods-GH/GroupFinderRIO#5]
### Description

I notice when trying to sign up for groups, when you click on them the group moves around on the list. then when you try and click on other groups it just bugs out and moves all over the place. 

### World of Warcraft Flavor

Retail (Default)

### Lua Error

None

### Reproduction Steps

i click on groups in window. 

### Last Good Version

not sure

**Comment by Jodsderechte** [comment]
Currently using both GroupFinderRio and Premade Groups Filter results in this. We are working on a fix but it's not done yet
