### ISSUE TITLE
everytime i try to select anything in LFG it keeps changing and reordering

### ISSUE THREAD

**Issue by badbrain79** [Jods-GH/GroupFinderRIO#6]
### Description

everytime i try to select anything in LFG it keeps changing and reordering
The same problems were also reported by others on Doc in the stream

### World of Warcraft Flavor

Retail (Default)

### Reproduction Steps

https://discord.com/channels/713882063169781870/713894653325475840/1284077028382867457

**Comment by Jodsderechte** [comment]
Ah i know why i forgot to add the activity id's of current expansion but they should have had a lua error like
20x GroupFinderRIO/GroupFinderRio.lua:434: No Raid Data for ID: 

Will be fixed in next version
