### ISSUE TITLE
lua error 9/14/2024

### ISSUE THREAD

**Issue by Milky063** [Jods-GH/GroupFinderRIO#7]
### Description

update to the lastest version and go this lua error....

### World of Warcraft Flavor

Retail (Default)

### Lua Error

1x GroupFinderRio/GroupFinderRio.lua:547: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@GroupFinderRio/GroupFinderRio.lua"]:547: in function <GroupFinderRio/GroupFinderRio.lua:541>
[string "=[C]"]: in function `LFGListSearchPanel_UpdateResults'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2199: in function `onEvent'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:262: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:171>
[string "=[C]"]: in function `ApplyToGroup'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:3322: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:3319>

Locals:
(*temporary) = <table> {
 1 = 7275
 2 = 6188
 3 = 7233
 4 = 7224
 5 = 6360
 6 = 7271
 7 = 7246
 8 = 7280
 9 = 7251
 10 = 7265
 11 = 7236
 12 = 7263
 13 = 7244
 14 = 7242
 15 = 7240
 16 = 7223
 17 = 7253
 18 = 7235
 19 = 7276
 20 = 7245
 21 = 7272
 22 = 7258
 23 = 7262
 24 = 7225
 25 = 7274
 26 = 7234
 27 = 7264
 28 = 7229
 29 = 7261
 30 = 7278
 31 = 7237
 32 = 7231
 33 = 7267
 34 = 7256
 35 = 7243
 36 = 7248
 37 = 7266
 38 = 7268
 39 = 7241
 40 = 7222
 41 = 7269
 42 = 7273
 43 = 7252
 44 = 7227
 45 = 7259
 46 = 7232
 47 = 7226
 48 = 7279
 49 = 7277
 50 = 7249
 51 = 7230
 52 = 7260
 53 = 7239
 54 = 7254
 55 = 7247
 56 = 7255
 57 = 7238
 58 = 7228
 59 = 7221
 60 = 7257
 61 = 7270
 62 = 7250
}
(*temporary) = 6360
(*temporary) = 6188
(*temporary) = nil

### Reproduction Steps

I just open the window for premade groups and this error happen

### Last Good Version

GroupFinderRio-v1.1.3.zip

**Comment by Milky063** [comment]
Also after refreshing the que in dungeons looking for group, the groups still randomly move around when you click on one. not fixed yet.

**Comment by Jodsderechte** [comment]
that was definitly working when i tested today and yesterday are you using PGF? cause the interaciton with that is still a WIP and will prob take till next week to be fixed see https://github.com/0xbs/premade-groups-filter/issues/269

**Comment by Milky063** [comment]
yes using “premade group finder” addon but had that addon first and worked fine with your WA. now that we have this addon its conflicting with it from the looks of it. your addon is just disable for now. 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jodsderechte** [comment]
I didn't creat any wa stuff before for this. Also you can just disable the sorting from the addon and it will be fine

**Comment by Milky063** [comment]
groupfinder rio was a weakaura till it told us to download the addon instead of the WA. thats what it said in the WA

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Milky063** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Milky063** [comment]
so rio was working before. now that people come over its causing this issue between them both.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Milky063** [comment]
Also i notice when you click on a group you have to go down and actually click on "signup" then click sign up again. PGF bye passes thia extra click and goes directly to the popup window "sign up" is there a way you can add this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Milky063** [comment]
Just got this error with PGF addon off,

1x GroupFinderRio/GroupFinderRio.lua:547: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@GroupFinderRio/GroupFinderRio.lua"]:547: in function <GroupFinderRio/GroupFinderRio.lua:541>
[string "=[C]"]: in function `LFGListSearchPanel_UpdateResults'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2199: in function `onEvent'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:262: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:171>
[string "=[C]"]: in function `ApplyToGroup'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:3322: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:3319>

Locals:
(*temporary) = <table> {
 1 = 10413
 2 = 10409
 3 = 10449
 4 = 10347
 5 = 10456
 6 = 10404
 7 = 10458
 8 = 10440
 9 = 10451
 10 = 10453
 11 = 10444
 12 = 10454
 13 = 10455
 14 = 10441
 15 = 10448
 16 = 10446
 17 = 10442
 18 = 10452
 19 = 10450
 20 = 10443
 21 = 10447
 22 = 10457
 23 = 10439
 24 = 10445
 25 = 10438
}
(*temporary) = 10456
(*temporary) = 10449
(*temporary) = nil

**Comment by Milky063** [comment]
just a heads up, i just got the last error with PGF addon off and yours the only one running.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jodsderechte** [comment]
Newest release should fix the error. The one click signup is available as an option you just have to toggle that on

**Comment by Milky063** [comment]
thank you sir

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
