### ISSUE TITLE
Cannot find a library instance of "AceConfigDialog-3.0".

### ISSUE THREAD

**Issue by divmehz** [Jods-GH/GroupFinderRIO#9]
### Description

Error upon logging in.

### World of Warcraft Flavor

Retail (Default)

### Lua Error

2x GroupFinderRio/Main.lua:3: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@AlterEgo/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@GroupFinderRio/Main.lua"]:3: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceConfigDialog-3.0"."

### Reproduction Steps

Log In, Did nothing more.

**Comment by divmehz** [comment]
another lua error that popped up in bugsack..

3x ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@AlterEgo/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@GroupFinderRio/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

**Comment by divmehz** [comment]
and another 

3x GroupFinderRio/Util/UtilFunctions.lua:2: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@AlterEgo/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@GroupFinderRio/Util/UtilFunctions.lua"]:2: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceConfigDialog-3.0"."

**Comment by Jodsderechte** [comment]
should be fixed in newest release

**Comment by divmehz** [comment]
No worries, looks like it disappeared when i installed the Ace3 developer addon - can use that as a workaround until the update comes through.

**Comment by Jodsderechte** [comment]
You don't even need that you just need any other addon that uses ace (wa is enough for example)

**Comment by divmehz** [comment]
Yeah i have WA, but it was still doing it, so ill remove the Ace3 Development addon once the update comes through as its fixed it for now. haha.
